FROM python:3.11-slim
WORKDIR /app
ENV PYTHONUNBUFFERED=1

# Copy file requirements trước
COPY requirements.txt .
# Cài đặt thư viện
RUN pip install --no-cache-dir -r requirements.txt

# Mở cổng và chạy Hot-reload với Uvicorn
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]